# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "1f741e8c03f85b4fe03fc25a5116e9db"
name = "subflow"
application_url = "https://subflow-delta.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/gdpr"

[access_scopes]
scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_product_listings,write_purchase_options"

[auth]
redirect_urls = [ "https://subflow-delta.vercel.app/api/auth" ]
