# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "1f741e8c03f85b4fe03fc25a5116e9db"
name = "subflow"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

[access_scopes]
scopes = "read_products,write_products,read_customers,write_customers,read_orders,write_orders,read_product_listings,write_purchase_options"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]